---
image:
  name: docker.io/library/nri-resource-policy-real-time
  tag: 0.9.0-4-gadd0bf33-dirty
  pullPolicy: IfNotPresent
config:
  reservedResources:
    cpu: 750m
  agent:
    nodeResourceTopology: true
    podResourceAPI: false
  control:
  log:
    source: true
    klog:
      skip_headers: true
    debug:
      - none
  instrumentation:
    httpEndpoint: ":8891"
    prometheusExport: false
    reportPeriod: 60s
    samplingRatePerMillion: 0
plugin-test:
  enableAPIs: false
resources:
  cpu: 500m
  memory: 512Mi
nri:
  plugin:
    index: 90
    annotations:
  runtime:
    patchConfig: false

tolerations: []
affinity: []
nodeSelector: []
podPriorityClassNodeCritical: true
